name: Manimatio unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        
      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup vcpkg cache
        uses: actions/cache@v4
        with:
          path: |
            .vcpkg/downloads
            .vcpkg/bincache
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Configure Project
        run: nix develop --command cmake --preset nix-dev 

      - name: Run unit tests
        run: nix develop --command just test-ci

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/nix-dev/test-results/*.xml